# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQJSTfKP-BJDPtysDdxo_VZhS7tW0vNy
"""

from flask import Flask , render_template , request
import cv2
from keras.models import load_model
import numpy as np
from werkzeug.utils import secure_filename

app = Flask(__name__,template_folder="Templates")

model = load_model('ND.h5')

@app.route('/' , methods = ['GET'])
def index():
  return render_template('sample bootstrap ai.html')
@app.route('/home' , methods = ['GET'])
def home():
  return render_template('sample bootstrap ai.html')

@app.route('/openCamera' , methods = ['GET' , 'POST'])
def predict():
  cap = cv2.VideoCapture(0)
  while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret == True:
      frame=cv2.flip(frame,1)
      output = frame.copy()
      frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
      frame = cv2.resize(frame,(64,64))
      x=np.expand_dims(x,axis=0)
      index=['Cyclone','Earthquake','Flood','Wildfire']
      y=np.argmax(model.predict(x),axis=1)
      #print(result)
      result = print(index[int(y)])
      cv2.putText(output,"Activity: {}".format(result),(10,100),cv2.FONT_HERSHEY_PLAIN,1,(0,25,255),1)
      # Display the resulting frame
      cv2.imshow('Frame',output) 
      if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    else: 
      break
  cap.release()
  cv2.destroyAllWindows()
  return render_template("index.html")

if __name__ == '__main__':
  app.run(host='0.0.0.0', port=8000, debug=True)

